/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Candidate {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'constituency' : string,
  'photo' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface MLA {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'constituency' : string,
  'photo' : ExternalBlob,
}
export interface Supporter {
  'id' : bigint,
  'name' : string,
  'joinedAt' : bigint,
  'address' : string,
  'phone' : string,
  'photo' : ExternalBlob,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCandidate' : ActorMethod<[string, string, string, ExternalBlob], bigint>,
  'addMLA' : ActorMethod<[string, string, string, ExternalBlob], bigint>,
  'addSupporter' : ActorMethod<
    [string, string, string, ExternalBlob, bigint],
    bigint
  >,
  'deleteCandidate' : ActorMethod<[bigint], undefined>,
  'deleteMLA' : ActorMethod<[bigint], undefined>,
  'deleteSupporter' : ActorMethod<[bigint], undefined>,
  'getAllCandidates' : ActorMethod<[], Array<Candidate>>,
  'getAllMLAs' : ActorMethod<[], Array<MLA>>,
  'getAllSupporters' : ActorMethod<[], Array<Supporter>>,
  'getCandidate' : ActorMethod<[bigint], Candidate>,
  'getMLA' : ActorMethod<[bigint], MLA>,
  'getSupporter' : ActorMethod<[bigint], Supporter>,
  'updateCandidate' : ActorMethod<
    [bigint, string, string, string, ExternalBlob],
    undefined
  >,
  'updateMLA' : ActorMethod<
    [bigint, string, string, string, ExternalBlob],
    undefined
  >,
  'verifyAdmin' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];